steps:
- name: gcr.io/google.com/cloudsdktool/cloud-sdk:slim
  args:
  - gcloud
  - functions
  - deploy
  - scrape
  - --entry-point=EntryPoint
  - --gen2
  - --region=${_LOCATION}
  - --runtime=go121
  - --source=scrape
  - --trigger-http
substitutions:
  _LOCATION: asia-northeast1
options:
  logging: CLOUD_LOGGING_ONLY
